# permissions for end users to view ccruntimes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ccruntime-viewer-role
rules:
  - apiGroups:
      - confidentialcontainers.org
    resources:
      - ccruntimes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - confidentialcontainers.org
    resources:
      - ccruntimes/status
    verbs:
      - get
