resources:
    - ../base
nameSuffix: -sgx-mode-sim
images:
    - name: quay.io/confidential-containers/runtime-payload
      newTag: enclave-cc-SIM-sample-kbc-
    - name: quay.io/confidential-containers/reqs-payload
      newTag: anewhash3
