name: Porter GHA Testing
run-name: ${{ github.actor }} is doing the porter GHA testing
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    #runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Log in to ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Construct tag for operator container image
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          WHICH_PR=$(gh pr view --json number -q .number)
          WHICH_COMMIT=$(git rev-parse --short HEAD)
          GHCR_IMG_TAG="PR${WHICH_PR}-${WHICH_COMMIT}"
          echo "GHCR_IMG_TAG=${GHCR_IMG_TAG}" >> $GITHUB_ENV
      - name: Sanity check tag
        run: |
          echo "ghcr img tag is: ${GHCR_IMG_TAG}"
      - name: build operator
        run: |
          docker build -t ghcr.io/portersrc/operator:${GHCR_IMG_TAG} .
      - name: push operator
        run: |
          docker push ghcr.io/portersrc/operator:${GHCR_IMG_TAG}
