name: Porter GHA Testing
run-name: ${{ github.actor }} is doing the porter GHA testing
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    #runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Log in to ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Basic echo and docker version
        run: |
          echo "Start"
          docker --version
          touch some_file.txt
          echo "github event number: ${{ github.event.number }}"
          echo "Endz"
      #- name: upload artifact
      #  uses: actions/upload-artifact@v4
      #  with:
      #    path: ./some_file.txt
      #- name: build operator
      #  run: |
      #    docker build -t ghcr.io/portersrc/operator:not-the-latest .
      #- name: push operator
      #  run: |
      #    docker push ghcr.io/portersrc/operator:not-the-latest
